version: "3"
services:
  mvc:
    image: josephisble/rest-mvc
    ports:
      - "5000:80"
    networks: 
      - net
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
  angular:
    image: josephisble/rest-angular
    ports:
      - "5001:80"
    networks:
      - net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  api:
    image: josephisble/rest-api
    ports:
      - "5002:80"
    networks:
      - net
    env_file: secrets.env
    deploy:
      replicas: 1
networks:
  net:
    
      