FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .

COPY CheapWareMVC.Test/*.csproj ./CheapWareMVC.Test/
COPY CheapWare.WebApp/*.csproj ./CheapWare.WebApp/
RUN dotnet restore

# copy everything else and build app
COPY . ./
WORKDIR /app/CheapWare.WebApp
RUN dotnet publish -c Release -o out


FROM microsoft/dotnet:2.1-aspnetcore-runtime AS runtime
WORKDIR /app
COPY --from=build /app/CheapWare.WebApp/out ./
ENTRYPOINT ["dotnet", "CheapWare.WebApp.dll"]
